rctest/urls.py
from django.contrib import admin
from django.urls import path
from recruit import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
                #   path('signup/', views.SignupView.as_view(), name='signup'),
                #   path('admin/', admin.site.urls),
                  path('', views.CustomLoginView.as_view(), name="main"),
                #   path('signout/', views.signout, name="signout"),
                #   path('notice/', views.notice, name="notice"),
                #   path('new', views.NewView.as_view(), name="new"),
                #   path('show', views.ShowView.as_view(), name="show"),
                #   path('edit/<int:pk>', views.EditView.as_view(), name="edit"),
                #   path('profile_update/<int:pk>', views.UserUpdate.as_view(), name="profile_update"),
                #   path('submit', views.submit, name="submit"),
                #   path('delete', views.delete, name="delete"),
                  path('guide', views.guide, name="guide"),
                  path('faq', views.faq, name="faq"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruit/models.py
from  __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

# Create your models here.

class Application(models.Model):
    created_by = models.ForeignKey(User, verbose_name='지원자 이름', on_delete=models.CASCADE , blank=True, null=True)
    q1 = models.TextField(verbose_name='질문1', blank=True, null=True)
    q2 = models.TextField(verbose_name='질문2', blank=True, null=True)
    q3 = models.TextField(verbose_name='질문3', blank=True, null=True)
    q4 = models.TextField(verbose_name='질문4', blank=True, null=True)
    q5 = models.FileField(upload_to='user', verbose_name='첨부파일', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='제출 날짜')
    final = models.BooleanField(default=False)

    def __str__(self):
        return str(self.created_by.last_name) + '의 지원서'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)#유저모델 onetoone
    phone = models.CharField(max_length=20, blank=True, verbose_name='연락처')
    major = models.CharField(max_length=255, verbose_name= '전공', null=True, blank=True)
    semester = models.IntegerField(verbose_name='누적학기', default=1)
    INTERVIEW_CHOICES = (
        ('WED', '25(수)'),
        ('THUR', '26(목)'),
        ('FRI', '27(금)'),
    )
    interview_date = MultiSelectField(
        max_length=20,
        choices=INTERVIEW_CHOICES,
        default='WED',
        verbose_name='희망 면접 날짜',
        null=True,
        blank=True
    )

    def __str__(self):
        return str(self.user.last_name) + '의 프로필'

recruit/forms.py
from django import forms
from .models import Application, Profile
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ['q1', 'q2', 'q3', 'q4', 'q5']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['password1', 'password2', 'email', 'last_name']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            'last_name',
        )
        
class SigninForm(ModelForm):
    class Meta:
        model = User
        widgets = {'password':forms.PasswordInput}
        fields = ['username','password']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

recruit/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.utils import timezone
from .models import Application, Profile, User
from django.contrib import messages
from django.contrib.auth.views import LoginView
from .forms import ApplicationForm, ProfileForm, SignupForm
from django.views.generic import ListView, CreateView, UpdateView
from django.http.response import HttpResponseRedirect
from datetime import datetime
from django.contrib.auth import logout


class NewView(CreateView):
    form_class = ApplicationForm
    template_name = 'new.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, '먼저 로그인을 해 주세요.')
            return HttpResponseRedirect(reverse('main'))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        user = self.request.user
        self.object.created_by = user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '임시 저장되었습니다.')
        return reverse('show')


class ShowView(ListView):
    template_name = 'show.html'
    model = Application
    context_object_name = 'new_context'

    def get_queryset(self):
        new_queryset = {}
        application = Application.objects.get(created_by=self.request.user)
        new_queryset['art'] = application
        return new_queryset

    def get_context_data(self, **kwargs):
        new_context = super().get_context_data(**kwargs)
        new_context['start'] = datetime.strptime("2020-03-16 10:00:00", '%Y-%m-%d %H:%M:%S')
        new_context['end'] = datetime.strptime("2020-03-22 22:00:00", '%Y-%m-%d %H:%M:%S')
        new_context['now'] = timezone.localtime()
        return new_context


class EditView(UpdateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'edit.html'

    def get(self, request, *args, **kwargs):
        if request.user != Application.objects.get(id=kwargs['pk']).created_by:
            messages.error(request, '수정 권한이 없습니다.')
            return HttpResponseRedirect(reverse('main'))
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, '임시 저장되었습니다.')
        return reverse('show')


class CustomLoginView(LoginView):
    context_object_name = 'new_context'

    def get_context_data(self, **kwargs):
        new_context = super().get_context_data(**kwargs)
        new_context['start'] = datetime.strptime("2020-03-16 10:00:00", '%Y-%m-%d %H:%M:%S')
        new_context['end'] = datetime.strptime("2020-03-22 22:00:00", '%Y-%m-%d %H:%M:%S')
        new_context['now'] = timezone.localtime()
        try:
            new_context['art'] = get_object_or_404(Application, created_by=self.request.user)
        except:
            pass
        return new_context


def submit(request):
    art = get_object_or_404(Application, created_by=request.user)
    art.final = True
    art.save()
    return render(request, 'registration/login.html', {'art':art})


def delete(request):
    art = get_object_or_404(Application, created_by=request.user)
    art.delete()
    return redirect('main')


class SignupView(CreateView):
    template_name = 'signup.html'
    form_class = SignupForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, '이미 로그인 되어있습니다.')
            return HttpResponseRedirect(render('main'))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        profile_form = ProfileForm(self.request.POST or None)
        profile = profile_form.save(commit=False)
        profile.user = self.object
        profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '회원가입 완료. 로그인 해 주세요.')
        return reverse('main')


class UserUpdate(UpdateView):
    model = Profile
    template_name = 'u_edit.html'
    form_class = ProfileForm

    def get(self, request, *args, **kwargs):
        if request.user.profile.id != kwargs['pk']:
            messages.error(request, '수정 권리가 없습니다')
            return HttpResponseRedirect(reverse('main'))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        profile_form = ProfileForm(request.POST or None)
        if profile_form.is_valid():
            profile = Profile.objects.get(user=request.user)
            profile.semester, profile.phone, profile.major = request.POST['semester'], request.POST['phone'], request.POST['major']
            profile.save()
            messages.success(request, '회원 정보 수정 완료')
            return HttpResponseRedirect(reverse('main'))
        else:
            messages.warning(request, '회원 정보 수정에 실패했습니다.')
            return HttpResponseRedirect(reverse('main'))


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('main'))


def guide(request):
    return render(request, 'guide.html')


def faq(request):
    return render(request, 'faq.html')

def notice(request):
    return render(request, 'notice.html')

recruit/templates/bootstrap.html
<!DOCTYPE html>
<html lang="utf-8">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>멋쟁이 사자처럼 - HUFS Global</title>
    {% block bootstrap4_extra_head %}{% endblock %}
</head>

<body>
<div class="body">
    {% block bootstrap4_before_content %}{% endblock %}
    {% block bootstrap4_content %} CONTENT {% endblock %}
    {% block bootstrap4_after_content %}{% endblock %}
    {% block bootstrap4_extra_script %}{% endblock %}
</div>
</body>

</html>

recruit/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<style>
#id_q1, #id_q2, #id_q3, #id_q4{
    max-width: 1000px; 
    height:400px; 
    font-size: large;
}
@media (max-width: 600px){
    #id_q1, #id_q2, #id_q3, #id_q4{
    font-size: 15px;
    height: 300px !important;
    padding: 10px !important;
    }
    .h5{
        font-size: 17px;
        line-height: 160%;
    }
    .container{
        padding: 0 28px;
    }
    .btn-lg{
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
}
</style>
    <div class="pl-md-5 py-3 ml-md-5 mt-5 ml-4" style="font-weight: bold;">
        <h3 style="font-weight: bold;"><span style="color: #f09837;">멋쟁이사자처럼</span><span style="color:#707070;"> HUFS Global</span></h3>
        <h4 style="font-weight: bold; color:#707070;">2020 상반기 리크루팅</h4>
        <h4 style="font-weight: bold; color:#707070;">지원서 수정</h4>
        <div class="border-bottom mr-5" style="max-width: 600px; height: 10px;"></div>
    </div>

<div class="container mt-5">
<form class="mt-3" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group mb-5">
        <label for="id_q1" class="mb-5 h5">1. 지원동기와 활동 목표를 기술하세요. (700자)</label>
        <textarea name="q1" class="form-control p-4" cols="40" rows="10" required="" id="id_q1">{{ application.q1 }}</textarea>
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q2" class="mb-5 h5">2. 타인과 협업했던 경험과 그 과정에서 자신이 수행한 역할에 대해 기술하세요. (700자)</label>
        <textarea name="q2" class="form-control p-4" cols="40" rows="10" required="" id="id_q2">{{ application.q2 }}</textarea>
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q3" class="mb-5 h5">3. IT 서비스로 구현하고 싶은 아이디어에 대해 구체적으로 기술하세요.<br>&nbsp&nbsp&nbsp (서비스가 해결하고자 하는 문제와 핵심 기능, 예상되는 사용자 등을 포함할 것) (800자)</label>
        <textarea name="q3" class="form-control p-4" cols="40" rows="10" required="" id="id_q3">{{ application.q3 }}</textarea>
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q4" class="mb-5 h5">4. 이용했던 서비스 중 인상 깊었던 부분이나 불편했던 점은 무엇이었고, 어떻게 발전/개선하면 좋을지 기술하세요. (700자)</label>
        <textarea name="q4" class="form-control p-4" cols="40" rows="10" required="" id="id_q4">{{ application.q4 }}</textarea>
    </div><br>
    <div class="form-group mb-5">
        <div class="mb-5 h5">5. 본인이 했던 활동이나 프로젝트 중 소개하고 싶은 것이 있다면 자유롭게 첨부해주시기 바랍니다. (필수X, 최대 200MB 파일 1개)</div>
        <label for="id_q5" class="btn btn-lg btn-light btn-outline-secondary">
            <input type="file" name="q5" style="display: none;" accept="" id="id_q5" onchange="$('#upload-file-info').html(this.files[0].name)">
            <span>파일 업로드</span>
        </label>
        <span class="label label-info ml-3" id="upload-file-info">{{ application.q5 }}</span>
    </div>

    <div class="text-center my-5 py-5">
        <input class="btn btn-lg btn-light btn-outline-warning" type="submit" value="임시저장하기">
    </div>
</form>
</div>


{% endblock %}

recruit/templates/new.html
{% extends 'base.html' %}
{% block content %}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<style>
 #id_q1, #id_q2, #id_q3, #id_q4{
    max-width: 1000px; 
    height:400px; 
    font-size: large;
}
@media (max-width: 600px){
    #id_q1, #id_q2, #id_q3, #id_q4{
    font-size: 15px;
    height: 300px !important;
    padding: 10px !important;
    }
    .h5{
        font-size: 17px;
        line-height: 160%;
    }
    .container{
        padding: 0 28px;
    }
    .btn-lg{
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
}
</style>
    <div class="pl-md-5 py-3 ml-md-5 mt-5 ml-4" style="font-weight: bold;">
        <h3 style="font-weight: bold;"><span style="color: #f09837;">멋쟁이사자처럼</span><span style="color:#ff8f66;"> HUFS Global</span></h3>
        <h4 style="font-weight: bold; color:#707070;">2020 상반기 리크루팅</h4>
        <h4 style="font-weight: bold; color:#707070;">지원서 작성</h4>
        <div class="border-bottom mr-5" style="max-width: 600px; height: 10px;"></div>
    </div>

<div class="container mt-5">
<form class="mt-3" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}
    <div class="form-group mb-5">
        <label for="id_q1" class="mb-5 h5">1. 지원동기와 활동 목표를 기술하세요. (700자)</label>
        <textarea name="q1" class="form-control p-4" id="id_q1"></textarea>
        (<span id="counter_q1">###</span>자)
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q2" class="mb-5 h5">2. 타인과 협업했던 경험과 그 과정에서 자신이 수행한 역할에 대해 기술하세요. (700자)</label>
        <textarea name="q2" class="form-control p-4" id="id_q2"></textarea>
        (<span id="counter_q2">###</span>자)
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q3" class="mb-5 h5">3. IT 서비스로 구현하고 싶은 아이디어에 대해 구체적으로 기술하세요.<br>&nbsp&nbsp&nbsp(서비스가 해결하고자 하는 문제와 핵심 기능, 예상되는 사용자 등을 포함할 것) (800자)</label>
        <textarea name="q3" class="form-control p-4" id="id_q3"></textarea>
        (<span id="counter_q3">###</span>자)
    </div><br>
    <div class="form-group mb-5">
        <label for="id_q4" class="mb-5 h5">4. 이용했던 서비스 중 인상 깊었던 부분이나 불편했던 점은 무엇이었고, 어떻게 발전/개선하면 좋을지 기술하세요. (700자)</label>
        <textarea name="q4" class="form-control p-4" id="id_q4"></textarea>
        (<span id="counter_q4">###</span>자)
    </div><br>
    <div class="form-group mb-5">
        <div class="mb-5 h5">5. 본인이 했던 활동이나 프로젝트 중 소개하고 싶은 것이 있다면 자유롭게 첨부해주시기 바랍니다. (필수X, 최대 200MB 파일 1개)</div>
        <label for="id_q5" class="btn btn-lg btn-light btn-outline-secondary">
            <input type="file" name="q5" style="display: none;" accept="" id="id_q5" onchange="$('#upload-file-info').html(this.files[0].name)">
            <span>파일 업로드</span>
        </label>
        <span class="label label-info ml-3" id="upload-file-info"></span>
    </div>
    <div class="text-center my-5 py-5">
        <input class="btn btn-lg btn-light btn-outline-warning" type="submit" value="임시저장하기">
    </div>
</form>
</div>

<script type="text/javascript">
    $(function() {
      $('#id_q1').keyup(function (e){
          var content = $(this).val().length;
          $('#counter_q1').html(content + '/700');
          if(content<=700){
              $('#counter_q1').css('color','black'); 
          }else{
              $('#counter_q1').css('color','red');
          }
      });
      $('#id_q1').keyup();

      $('#id_q2').keyup(function (e){
          var content = $(this).val().length;
          $('#counter_q2').html(content + '/700');
          if(content<=700){
              $('#counter_q2').css('color','black'); 
          }else{
              $('#counter_q2').css('color','red');
          }
      });
      $('#id_q2').keyup();

      $('#id_q3').keyup(function (e){
          var content = $(this).val().length;
          $('#counter_q3').html(content + '/700');
          if(content<=700){
              $('#counter_q3').css('color','black'); 
          }else{
              $('#counter_q3').css('color','red');
          }
      });
      $('#id_q3').keyup();

      $('#id_q4').keyup(function (e){
          var content = $(this).val().length;
          $('#counter_q4').html(content + '/700');
          if(content<=700){
              $('#counter_q4').css('color','black'); 
          }else{
              $('#counter_q4').css('color','red');
          }
      });
      $('#id_q4').keyup();
    });
</script>



{% endblock %}

<!-- {{art.q4}} -->

recruit/templates/show.html
{% extends 'base.html' %}
{% block content %}
<style>
    .a-yellow{
    color:#f09837;
    }

    .a-yellow:hover {
    color: #8a551d;
    text-decoration:none
    }
    pre{
        font-family: 'Nanum Gothic', sans-serif !important; 
        white-space: pre-wrap;
        font-size: large;
    }
    @media (max-width: 600px){
        #id_q1, #id_q2, #id_q3, #id_q4{
            padding: 10px !important;
        }
        pre{
            font-size: 14px;
        }
        .h5{
            font-size: 17px;
            line-height: 160%;
        }
        .container{
            padding-right: 20px;
            padding-left: 20px;
        }
        .btn-lg{
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: .25rem;
        }
    }
</style>
    <div class="pl-md-5 py-3 ml-md-5 mt-5 ml-4" style="font-weight: bold;">
        <h3 style="font-weight: bold;"><span style="color: #f09837;">멋쟁이사자처럼</span><span style="color:#ff8f66;"> 서강대학교</span></h3>
        <h4 style="font-weight: bold; color:#707070;">2020 상반기 리크루팅</h4>
        <h4 style="font-weight: bold; color:#707070;">지원서 보기</h4>
        <div class="border-bottom mr-5" style="max-width: 600px; height: 10px;"></div>
    </div>

<div class="container mt-5">
    <div class="form-group mb-5">
        <label for="id_q1" class="mb-4 h5 font-weight-bold">1. 지원동기와 활동 목표를 기술하세요. (700자)</label>
        <div name="q1" class="p-5 mt-0 mt-md-4 border rounded" style="max-width: 1000px; min-height:400px;" id="id_q1"><pre>{{ object_list.art.q1 }}</pre></div>
    </div><br><br>
    <div class="form-group mb-5">
        <label for="id_q2" class="mb-4 h5 font-weight-bold">2. 타인과 협업했던 경험과 그 과정에서 자신이 수행한 역할에 대해 기술하세요. (700자)</label>
        <div name="q2" class="p-5 mt-0 mt-md-4 border rounded" style="max-width: 1000px; min-height:400px;" id="id_q2"><pre>{{ object_list.art.q2 }}</pre></div>
    </div><br><br>
    <div class="form-group mb-5">
        <label for="id_q3" class="mb-4 h5 font-weight-bold">3. IT 서비스로 구현하고 싶은 아이디어에 대해 구체적으로 기술하세요.<br>&nbsp&nbsp&nbsp(서비스가 해결하고자 하는 문제와 핵심 기능, 예상되는 사용자 등을 포함할 것) (800자)</label>
        <div name="q3" class="p-5 mt-0 mt-md-4 border rounded" style="max-width: 1000px; min-height:400px;" id="id_q3"><pre>{{ object_list.art.q3 }}</pre></div>
    </div><br><br>
    <div class="form-group mb-5">
        <label for="id_q4" class="mb-4 h5 font-weight-bold">4. 이용했던 서비스 중 인상 깊었던 부분이나 불편했던 점은 무엇이었고, 어떻게 발전/개선하면 좋을지 기술하세요. (700자)</label>
        <div name="q4" class="p-5 mt-0 mt-md-4 border rounded" style="max-width: 1000px; min-height:400px;" id="id_q4"><pre>{{ object_list.art.q4 }}</pre></div>
    </div><br><br>
    <div class="form-group mb-5">
        <div class="mb-4 h5 font-weight-bold">5. 본인이 했던 활동이나 프로젝트 중 소개하고 싶은 것이 있다면 자유롭게 첨부해주시기 바랍니다. (필수X, 최대 200MB 파일 1개)</div>
        {% if object_list.art.q5 %}
            <div class="ml-2">{{ object_list.art.q5.name }}</div>
        {% endif %}
    </div><br><br>
    <div class="form-group mb-5">
        <span class="mb-4 h5 font-weight-bold">희망 면접일:</span>
        <span class="ml-2">
            {{ request.user.profile.interview_date }}
        </span>
    </div>
    {% if now|date:"YmdHi" < end|date:"YmdHi" %}
        {% if object_list.art.final == False %}
        <div class="text-center mt-5 mb-4 pt-5">
            <span style="color: red;">*제출 후에는 지원서 수정이 불가능합니다.</span>
        </div><br>
            <div class="text-center">
                <a href="{% url 'edit' object_list.art.id %}" class="btn btn-lg btn-light btn-outline-secondary mx-1 mb-2">수정하기</a>
                <button data-toggle="modal" data-target="#submitAlert" class="btn btn-lg btn-light btn-outline-secondary mx-1 mb-2">제출하기</button>
                
                <!-- submit alert modal -->
                <div class="modal fade" id="submitAlert" tabindex="-1" role="dialog" aria-labelledby="submitAlertLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="submitAlertLabel">잠시만요!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                        제출 후 수정할 수 없습니다. <br>제출하시겠어요?
                        </div>
                        <div class="modal-footer">
                        <a href="{% url 'submit' %}" class="btn btn-light btn-outline-warning">제출하기</a>
                        <button type="button" class="btn btn-light btn-outline-secondary" data-dismiss="modal">돌아가기</button>
                        </div>
                    </div>
                    </div>
                </div>
               
                <button data-toggle="modal" data-target="#deleteAlert" class="btn btn-lg btn-light btn-outline-secondary mx-1 mb-2">삭제하기</button>
                
                <!-- delete alert modal -->
                <div class="modal fade" id="deleteAlert" tabindex="-1" role="dialog" aria-labelledby="deleteAlertLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="deleteAlertLabel">잠시만요!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                        정말 삭제하시겠어요? <br>삭제 후 복구할 수 없습니다.
                        </div>
                        <div class="modal-footer">
                        <a href="{% url 'delete' %}" class="btn btn-light btn-outline-warning">삭제하기</a>
                        <button type="button" class="btn btn-light btn-outline-secondary" data-dismiss="modal">돌아가기</button>
                        </div>
                    </div>
                    </div>
                </div>
                
            </div>
        {% endif %}
    {% endif %}<br><br><br><br>
    <a href="{% url 'main' %}" class="mr-5 a-yellow" style="float: right;" >돌아가기</a>
    <br>
</div>


{% endblock %}